# Workload: PCS-Only Topology - PCS with rack constraint
# Test scenario: PCS with rack constraint, PCSG without constraint, standalone clique
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: tas-sl-pcs-only
  labels:
    app: tas-sl-pcs-only
spec:
  replicas: 1
  template:
    topologyConstraint:
      packDomain: rack
    podCliqueScalingGroups:
      - name: workers
        replicas: 2
        minAvailable: 2
        cliqueNames:
          - worker
    cliques:
      - name: worker
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: worker
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: grove.io/podclique
                          operator: In
                          values:
                            - tas-sl-pcs-only-0-workers-0-worker
                    topologyKey: kubernetes.io/hostname
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: worker
                image: registry:5001/busybox:latest
                command: ["sleep", "infinity"]
                resources:
                  requests:
                    memory: 10Mi
      - name: router
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: router
          replicas: 2
          minAvailable: 2
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchExpressions:
                        - key: grove.io/podclique
                          operator: In
                          values:
                            - tas-sl-pcs-only-0-router
                    topologyKey: kubernetes.io/hostname
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: router
                image: registry:5001/busybox:latest
                command: ["sleep", "infinity"]
                resources:
                  requests:
                    memory: 10Mi
