# Workload: Disaggregated Inference - Multi-replica PCS with 3-level topology hierarchy
# Test scenario: PCS (block) with 2 replicas, 2 PCSGs (rack), and PCLQ-level constraint (host)
---
apiVersion: grove.io/v1alpha1
kind: PodCliqueSet
metadata:
  name: tas-pcs-multi-pcsg
  labels:
    app: tas-pcs-multi-pcsg
spec:
  replicas: 2
  template:
    topologyConstraint:
      packDomain: block
    podCliqueScalingGroups:
      - name: decoder
        replicas: 2
        minAvailable: 1
        topologyConstraint:
          packDomain: rack
        cliqueNames:
          - dworker
          - dleader
      - name: prefill
        replicas: 2
        minAvailable: 1
        topologyConstraint:
          packDomain: rack
        cliqueNames:
          - pworker
          - pleader
    cliques:
      - name: dworker
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: dworker
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: worker
                image: registry:5001/busybox:latest
                command: ["sleep", "infinity"]
                resources:
                  requests:
                    memory: 40Mi
      - name: dleader
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: dleader
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: leader
                image: registry:5001/busybox:latest
                command: ["sleep", "infinity"]
                resources:
                  requests:
                    memory: 40Mi
      - name: pworker
        topologyConstraint:
          packDomain: host
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: pworker
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: worker
                image: registry:5001/busybox:latest
                command: ["sleep", "infinity"]
                resources:
                  requests:
                    memory: 40Mi
      - name: pleader
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: pleader
          replicas: 1
          minAvailable: 1
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: leader
                image: registry:5001/busybox:latest
                command: ["sleep", "infinity"]
                resources:
                  requests:
                    memory: 40Mi
      - name: router
        labels:
          kai.scheduler/queue: test
        spec:
          roleName: router
          replicas: 2
          minAvailable: 2
          podSpec:
            schedulerName: kai-scheduler
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: node_role.e2e.grove.nvidia.com
                          operator: In
                          values:
                            - agent
            tolerations:
              - key: node_role.e2e.grove.nvidia.com
                operator: Equal
                value: agent
                effect: NoSchedule
            containers:
              - name: router
                image: registry:5001/busybox:latest
                command: ["sleep", "infinity"]
                resources:
                  requests:
                    memory: 40Mi
